services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    container_name: sqlserverCC
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Cc202505!
      - MSSQL_PID=Express
    # entrypoint: ["bash", "-c", "echo 'Rodando setup'; mkdir -p /app/logs && tail -f /dev/null"]
